### ISSUE TITLE
How do I derive taproot addresses?

### ISSUE THREAD

**Issue by meglio** [Anderson-Juhasc/bip84#11]
Hi, is it possible to use this library to derive taproot addresses from xpub/zpub?

**Comment by Anderson-Juhasc** [comment]
Hi @meglio, i have made the bip86 to generate taproot addresses to, you can see here:  https://github.com/Anderson-Juhasc/bip86

**Comment by meglio** [comment]
@Anderson-Juhasc but that does not work with `zprv/zpub` and `vprv/vpub`.

**Comment by Anderson-Juhasc** [comment]
@meglio you can convert the zprv to xprv or just use the same mnemonic words with the bip86 and you can get the xprv for that.

I think in these lines I converted the xprv to zprv: https://github.com/Anderson-Juhasc/bip84/blob/master/src/index.js#L82-L109 and you can do the opposite.

Let me know if it helped you.

Cheers!
